sudo: required
services:
  - docker
language: bash

env:
  - REPO=lawliet89/telegram-dice-roller

script:
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - bash docker/build.sh "${REPO}" "${TRAVIS_BRANCH}" "Dockerfile-pi3"

deploy:
  provider: script
  script: bash dcker/push.sh "${REPO}" "${TRAVIS_BRANCH}"
  on:
    # branch: master
    tags: true

branches:
  only:
  - master
