# Dockerfile for Raspberry Pi3
FROM balenalib/raspberrypi3-debian-python:3.7-latest

WORKDIR /app

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY ./ ./

CMD ["python", "diceroller.py"]
